#include "test.h"
#include "hmac-blake2b.h"
#include "../hmac-blake2b.h"

static void test_values(const char *key, const char *message, const char *expected)
{
	struct hmac_blake2b_state state;
	unsigned char buf[64];
	char hex[129] = {};
	unsigned int i;

	hmac_blake2b_init(&state, key, strlen(key));
	hmac_blake2b_update(&state, message, strlen(message));
	hmac_blake2b_final(&state, buf);

	for (i = 0; i < 64; i++) {
		sprintf(hex + (i * 2), "%02x", buf[i]);
	}

	ck_assert_str_eq(expected, hex);

	hmac_blake2b_wipe_state(&state);

}

/* the test vectors were generated by a python script */
START_TEST(test_hmac_blake2b)
{
	test_values("key1", "message1",
		"1e344571a142af9e1684e3371e4ba6b267424d7bee5dc7c3c57aec760a96b2f9"
		"f2af23de6b8eb77d9f4d9bc9c890ef37de32af0032e2cecee93736e74fcd509b");

	test_values("key2", "message2",
		"29b3a353121a5f0fc482523e69ac6a26994fa1e780c8f88bc6457852b9a17920"
		"2ca1c51b4fd32fc0e362e98d28e9de19237ba87278023711e54d89e74f3813ad");

	test_values("a long key for HMAC purposes", "another test message",
		"645312d15794966a8bbed52d0dcfbfc1377d4307b65c7ac0b414a561ab6dbd1b"
		"b7e3d562a093ba8f70eb1bae18046179f7173edaf7f20bad187ae1f43d5425d4");
}
END_TEST

void register_hmac_blake2b_tests(struct TCase *test_case)
{
	tcase_add_test(test_case, test_hmac_blake2b);
}
